# Generated by Django 5.0.6 on 2024-12-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaPabellon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_medico', models.CharField(max_length=100)),
                ('rut_medico', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=100)),
                ('tipo_cirugia', models.CharField(max_length=100)),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('rut_paciente', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('equipo_medico', models.CharField(max_length=200)),
            ],
        ),
    ]
